// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HomeScreen from "./HomeScreen.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Stacks_component_Provider from "@mobily/stacks/src/Stacks_component_Provider.bs.js";

function useIsDarkMode(param) {
  return Belt_Option.getWithDefault(Belt_Option.map(Caml_option.null_to_opt(ReactNative.useColorScheme()), (function (scheme) {
                    return scheme === "dark";
                  })), false);
}

function App$app(Props) {
  return React.createElement(Stacks_component_Provider.make, {
              spacing: 4,
              children: React.createElement(HomeScreen.make, {})
            });
}

var app = App$app;

export {
  useIsDarkMode ,
  app ,
  
}
/* react Not a pure module */
