// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactNative from "react-native";

function ExerciseRow(Props) {
  var index = Props.index;
  var title = Props.title;
  var dispatch = Props.dispatch;
  return React.createElement(ReactNative.Pressable, {
              children: (function (interactionState) {
                  return React.createElement(ReactNative.Text, {
                              children: title,
                              key: String(index)
                            });
                }),
              onPress: (function (param) {
                  return Curry._1(dispatch, {
                              TAG: /* RemoveExercise */1,
                              _0: index
                            });
                })
            });
}

var make = ExerciseRow;

export {
  make ,
  
}
/* react Not a pure module */
