// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactNative from "react-native";

function ExerciseInput(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setExerciseInput = match[1];
  return React.createElement(ReactNative.TextInput, {
              onChangeText: (function (text) {
                  return Curry._1(setExerciseInput, (function (param) {
                                return text;
                              }));
                })
            });
}

var make = ExerciseInput;

export {
  make ,
  
}
/* react Not a pure module */
