// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Theme from "./Theme.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";
import * as VectorIcons from "@expo/vector-icons";

var styles = ReactNative.StyleSheet.create({
      row: {
        borderColor: Theme.color.grey_200,
        borderWidth: 1,
        flexDirection: "row",
        justifyContent: "space-between",
        paddingHorizontal: 8
      },
      input: {
        flex: 1
      }
    });

function ExerciseInput(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setExerciseInput = match[1];
  return React.createElement(ReactNative.View, {
              style: styles.row,
              children: null
            }, React.createElement(ReactNative.TextInput, {
                  onChangeText: (function (text) {
                      return Curry._1(setExerciseInput, (function (param) {
                                    return text;
                                  }));
                    }),
                  style: styles.input
                }), React.createElement(ReactNative.Pressable, {
                  children: (function (interactionState) {
                      return React.createElement(VectorIcons.Ionicons, {
                                  name: "add",
                                  size: 32,
                                  color: "orange"
                                });
                    }),
                  onPress: (function (param) {
                      console.log("addExercise()");
                      return Curry._1(setExerciseInput, (function (param) {
                                    return "";
                                  }));
                    })
                }));
}

var make = ExerciseInput;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
