// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "./Store.bs.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as ExerciseRow from "./ExerciseRow.bs.js";
import * as ReactNative from "react-native";
import * as ExerciseInput from "./ExerciseInput.bs.js";
import * as Stacks_component_Box from "@mobily/stacks/src/Stacks_component_Box.bs.js";
import * as Stacks_component_Stack from "@mobily/stacks/src/Stacks_component_Stack.bs.js";

var orange_500 = "rgb(100, 50, 50)";

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: orange_500,
        marginTop: 62,
        paddingHorizontal: 24
      },
      sectionContainer: {
        paddingHorizontal: 24
      },
      sectionTitle: {
        fontSize: 24,
        fontWeight: "600"
      },
      sectionDescription: {
        fontSize: 18,
        fontWeight: "400",
        marginTop: 8
      },
      highlight: {
        fontWeight: "700"
      },
      exerciseList: {
        alignItems: "center",
        justifyContent: "center"
      }
    });

function HomeScreen(Props) {
  var match = React.useReducer(Store.reducer, Store.initialState);
  var dispatch = match[1];
  return React.createElement(ReactNative.ScrollView, {
              contentInsetAdjustmentBehavior: "automatic",
              children: React.createElement(Stacks_component_Box.make, {
                    padding: [8],
                    style: styles.container,
                    children: null
                  }, React.createElement(ReactNative.View, {
                        style: styles.sectionContainer,
                        children: React.createElement(ReactNative.Text, {
                              children: "Exercises",
                              style: styles.sectionTitle
                            })
                      }), React.createElement(ExerciseInput.make, {
                        dispatch: dispatch
                      }), React.createElement(Stacks_component_Stack.make, {
                        space: [6],
                        style: styles.exerciseList,
                        children: Belt_Array.mapWithIndex(match[0].exercises, (function (index, x) {
                                return React.createElement(ExerciseRow.make, {
                                            index: index,
                                            title: x.title,
                                            dispatch: dispatch
                                          });
                              }))
                      }))
            });
}

var make = HomeScreen;

export {
  orange_500 ,
  styles ,
  make ,
  
}
/* styles Not a pure module */
