// Generated by ReScript, PLEASE EDIT WITH CARE


var Header = {};

var ReloadInstructions = {};

var LearnMoreLinks = {};

var DebugInstructions = {};

export {
  Header ,
  ReloadInstructions ,
  LearnMoreLinks ,
  DebugInstructions ,
  
}
/* No side effect */
