// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

var dummyExercises = [
  {
    id: 0,
    title: "Bench Press",
    bodyPart: "Chest",
    equipment: "Barbell"
  },
  {
    id: 1,
    title: "Press Ups",
    bodyPart: "Chest",
    equipment: "Body"
  },
  {
    id: 2,
    title: "Military Press",
    bodyPart: "Deltoids",
    equipment: "Barbell"
  },
  {
    id: 3,
    title: "Squat",
    bodyPart: "Legs",
    equipment: "Barbell"
  },
  {
    id: 4,
    title: "Deadlift",
    bodyPart: "Legs",
    equipment: "Barbell"
  },
  {
    id: 5,
    title: "Pull Ups",
    bodyPart: "Back",
    equipment: "Bar"
  },
  {
    id: 6,
    title: "Lunges",
    bodyPart: "Legs",
    equipment: "Dumbell"
  },
  {
    id: 7,
    title: "Chest Flys",
    bodyPart: "Chest",
    equipment: "Dumbell"
  },
  {
    id: 8,
    title: "Shoulder Press",
    bodyPart: "Deltoids",
    equipment: "Dumbell"
  }
];

var initialState = {
  exercises: dummyExercises,
  nextId: 5
};

function reducer(state, action) {
  if (action.TAG === /* AddExercise */0) {
    var exercises = Belt_Array.concat(state.exercises, [{
            id: state.nextId,
            title: action.title,
            bodyPart: action.bodyPart,
            equipment: "HardCoded"
          }]);
    return {
            exercises: exercises,
            nextId: state.nextId
          };
  }
  var id = action._0;
  var exercises$1 = state.exercises.filter(function (ex) {
        return ex.id !== id;
      });
  return {
          exercises: exercises$1,
          nextId: state.nextId
        };
}

export {
  dummyExercises ,
  initialState ,
  reducer ,
  
}
/* No side effect */
