// Generated by ReScript, PLEASE EDIT WITH CARE


var color = {
  blue_100: "rgb(0, 71, 171)",
  orange_500: "rgb(255, 102, 0)",
  grey_100: "#ECECEC",
  grey_200: "#D4D4D4"
};

export {
  color ,
  
}
/* No side effect */
